variables:
  GIT_SUBMODULE_STRATEGY: recursive
  TERM: linux
  GIT_STRATEGY: clone

cours:
  stage: build
  only:
    - master@stepan/time-series
  script:
    - make
    - scp cours/chapitre-1.pdf /puck/www/le-mans.adjemian.eu/séries-temporelles
    - scp cours/chapitre-2.pdf /puck/www/le-mans.adjemian.eu/séries-temporelles
    - scp cours/chapitre-3.pdf /puck/www/le-mans.adjemian.eu/séries-temporelles
    - scp cours/chapitre-4.pdf /puck/www/le-mans.adjemian.eu/séries-temporelles
    - scp ds/*.pdf /puck/www/le-mans.adjemian.eu/séries-temporelles/examens
  artifacts:
    paths:
      - cours/chapitre-1.pdf
      - cours/chapitre-2.pdf
      - cours/chapitre-3.pdf
      - cours/chapitre-4.pdf
  tags:
    - stepan@puck
